In [38]:
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt
from dt_apriltags import Detector
import lane_detection

In [39]:
img = cv2.imread('rov_pool.jpg')

In [40]:
lines = lane_detection.detect_lines(img, 10, 100, apertureSize=3, minLineLength=100, maxLineGap=10)
print(lines)

[[[ 725  499  942  876]]

 [[1240  484 1565  615]]

 [[1282  463 1562  565]]

 [[ 701  456  821  665]]

 [[1459  527 1565  565]]

 [[ 714  731  758  877]]

 [[ 639  482  720  749]]

 [[1138  410 1306  471]]

 [[1095  422 1195  464]]]


In [41]:
(slopes, intercepts) = lane_detection.get_slopes_intercepts(lines)
lined_img = lane_detection.draw_lanes(img, lines)

In [42]:
plt.imshow(cv2.cvtColor(lined_img, cv2.COLOR_BGR2RGB))

error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
